tasks:
  - name: terraform
    before: |
      source ./nbt/set_tf_alias
      source ./nbt/installHashiTerraformCli
      source ./nbt/generate_tfrc_creds
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./nbt/set_tf_alias
      source ./nbt/installAmazonAWSCli
     
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform